#!/bin/bash

osch=0
echo "1. Unix (Sun OS)"
echo "2. Linux (Red Hat)"

echo -n "Select your OS choise [1 or 2]? "
read osch
if [ $osch -eq 1 ]
then
	echo "You pick Unix (Sun OS)"
else #### nested if i.e if within if ######
		if [ $osch -eq 2 ]
		then
			echo "You pick Linux (Red Hat)"
		else
			echo "What, you don't like Unix/Linux OS?"
		fi
fi
